apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_geoconn"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres-geoconn"
  DB_PORT: "5432"
  KAFKA_URL: zub-release-kafka.default.svc.cluster.local:9092
  KAFKA_TOPIC: test
metadata:
  name: config-location-consumer-map