apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_connections"
  DB_NAME: "connections"
  DB_HOST: "postgres-connections"
  DB_PORT: "5432"
  KAFKA_URL: localhost:9092
  KAFKA_TOPIC: test
metadata:
  name: config-location-consumer-map